language: python
python:
  - "2.7"
services:
  - mongodb
  - memcached
before_install:
  - sudo apt-get install beanstalkd
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - make tests
after_script:
  - coveralls